# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ashkrai/backend:0.4.1
          imagePullPolicy: IfNotPresent  # Ensure the image isn't pulled unnecessarily
          ports:
            - containerPort: 7000
     
---
# SERVICE 
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP
