apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # The port to be exposed for the service (can be accessed externally)
      targetPort: 3000  # Port on which the frontend container is running
  type: ClusterIP  # Exposing within the cluster
