apiVersion: v1
kind: Service
metadata:
  name: connect-backend-service
spec:
  selector:
    app: connect-backend  # Matches the app label in the deployment
  ports:
    - protocol: TCP
      port: 80            # Expose port 80 externally
      targetPort: 7000     # The container's internal port
  type: ClusterIP         # Service type (can be LoadBalancer or NodePort if needed)
